import { defineTool } from "@lovable.dev/mcp-js";
import { z } from "zod";

export default defineTool({
  name: "draft_contract_clause",
  title: "Draft a PiTrade contract clause",
  description:
    "Given a deal description, return a structured Markdown contract clause block the user can paste into a new PiTrade contract. Does not create anything on the platform.",
  inputSchema: {
    goods: z.string().min(1).describe("Description of the goods (e.g. 'Arabica green coffee beans, grade 1')."),
    quantity: z.number().positive().describe("Numeric quantity."),
    unit: z.string().min(1).describe("Unit of measure (e.g. 'tonnes', 'units', 'boxes')."),
    originCountry: z.string().min(1),
    destinationCountry: z.string().min(1),
    incoterm: z.enum(["EXW", "FOB", "CIF", "DAP", "DDP"]),
    amountPi: z.number().positive().describe("Total price in π (Pi)."),
    deliveryWindow: z.string().min(1).describe("Delivery window, e.g. '30-45 days from funding'."),
    buyer: z.string().min(1).describe("Buyer identifier (Pi username or company)."),
    seller: z.string().min(1).describe("Seller identifier (Pi username or company)."),
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: (input) => {
    const md = `# Trade Contract — Draft

**Parties**
- Buyer: ${input.buyer}
- Seller: ${input.seller}

**Goods**
- ${input.goods}
- Quantity: ${input.quantity} ${input.unit}
- Origin: ${input.originCountry} → Destination: ${input.destinationCountry}

**Commercial terms**
- Incoterm: ${input.incoterm}
- Price: π ${input.amountPi.toLocaleString()}
- Delivery window: ${input.deliveryWindow}

**Payment & escrow**
1. Buyer funds the full amount from their Pi Wallet upon contract acceptance.
2. Funds are held and released against shipment milestones (loading, transit, delivery).
3. Disputes pause release until both parties confirm resolution.

**Compliance**
- Seller warrants goods conform to description and origin declaration.
- Buyer is responsible for import clearance unless Incoterm is DDP.

_This draft is generated by PiTrade Copilot. Both parties must review before signing._`;
    return { content: [{ type: "text", text: md }] };
  },
});
