/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrustRouteImport } from './routes/trust'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ContractsIndexRouteImport } from './routes/contracts.index'
import { Route as ContractsIdRouteImport } from './routes/contracts.$id'
import { Route as ContractsNewRouteImport } from './routes/contracts.new'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPiSessionRouteImport } from './routes/api/pi.session'
import { Route as ApiPiVerifyRouteImport } from './routes/api/pi.verify'
import { Route as ApiPiPaymentsApproveRouteImport } from './routes/api/pi.payments.approve'
import { Route as ApiPiPaymentsCancelRouteImport } from './routes/api/pi.payments.cancel'
import { Route as ApiPiPaymentsCompleteRouteImport } from './routes/api/pi.payments.complete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustRoute = TrustRouteImport.update({
  id: '/trust',
  path: '/trust',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIndexRoute = ContractsIndexRouteImport.update({
  id: '/contracts/',
  path: '/contracts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsIdRoute = ContractsIdRouteImport.update({
  id: '/contracts/$id',
  path: '/contracts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsNewRoute = ContractsNewRouteImport.update({
  id: '/contracts/new',
  path: '/contracts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPiSessionRoute = ApiPiSessionRouteImport.update({
  id: '/api/pi/session',
  path: '/api/pi/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPiVerifyRoute = ApiPiVerifyRouteImport.update({
  id: '/api/pi/verify',
  path: '/api/pi/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPiPaymentsApproveRoute = ApiPiPaymentsApproveRouteImport.update({
  id: '/api/pi/payments/approve',
  path: '/api/pi/payments/approve',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPiPaymentsCancelRoute = ApiPiPaymentsCancelRouteImport.update({
  id: '/api/pi/payments/cancel',
  path: '/api/pi/payments/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPiPaymentsCompleteRoute = ApiPiPaymentsCompleteRouteImport.update({
  id: '/api/pi/payments/complete',
  path: '/api/pi/payments/complete',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/contracts/new': typeof ContractsNewRoute
  '/contracts/': typeof ContractsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/pi/session': typeof ApiPiSessionRoute
  '/api/pi/verify': typeof ApiPiVerifyRoute
  '/api/pi/payments/approve': typeof ApiPiPaymentsApproveRoute
  '/api/pi/payments/cancel': typeof ApiPiPaymentsCancelRoute
  '/api/pi/payments/complete': typeof ApiPiPaymentsCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/contracts/new': typeof ContractsNewRoute
  '/contracts': typeof ContractsIndexRoute
  '/services': typeof ServicesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/pi/session': typeof ApiPiSessionRoute
  '/api/pi/verify': typeof ApiPiVerifyRoute
  '/api/pi/payments/approve': typeof ApiPiPaymentsApproveRoute
  '/api/pi/payments/cancel': typeof ApiPiPaymentsCancelRoute
  '/api/pi/payments/complete': typeof ApiPiPaymentsCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/guide': typeof GuideRoute
  '/how-it-works': typeof HowItWorksRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trust': typeof TrustRoute
  '/wallet': typeof WalletRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/contracts/$id': typeof ContractsIdRoute
  '/contracts/new': typeof ContractsNewRoute
  '/contracts/': typeof ContractsIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/pi/session': typeof ApiPiSessionRoute
  '/api/pi/verify': typeof ApiPiVerifyRoute
  '/api/pi/payments/approve': typeof ApiPiPaymentsApproveRoute
  '/api/pi/payments/cancel': typeof ApiPiPaymentsCancelRoute
  '/api/pi/payments/complete': typeof ApiPiPaymentsCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/guide'
    | '/how-it-works'
    | '/mcp'
    | '/sitemap.xml'
    | '/trust'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/contracts/$id'
    | '/contracts/new'
    | '/contracts/'
    | '/services/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/pi/session'
    | '/api/pi/verify'
    | '/api/pi/payments/approve'
    | '/api/pi/payments/cancel'
    | '/api/pi/payments/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/guide'
    | '/how-it-works'
    | '/mcp'
    | '/sitemap.xml'
    | '/trust'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/contracts/$id'
    | '/contracts/new'
    | '/contracts'
    | '/services'
    | '/.mcp/invoke-tool/$tool'
    | '/api/pi/session'
    | '/api/pi/verify'
    | '/api/pi/payments/approve'
    | '/api/pi/payments/cancel'
    | '/api/pi/payments/complete'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/guide'
    | '/how-it-works'
    | '/mcp'
    | '/sitemap.xml'
    | '/trust'
    | '/wallet'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/contracts/$id'
    | '/contracts/new'
    | '/contracts/'
    | '/services/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/pi/session'
    | '/api/pi/verify'
    | '/api/pi/payments/approve'
    | '/api/pi/payments/cancel'
    | '/api/pi/payments/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  GuideRoute: typeof GuideRoute
  HowItWorksRoute: typeof HowItWorksRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrustRoute: typeof TrustRoute
  WalletRoute: typeof WalletRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  ContractsIdRoute: typeof ContractsIdRoute
  ContractsNewRoute: typeof ContractsNewRoute
  ContractsIndexRoute: typeof ContractsIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPiSessionRoute: typeof ApiPiSessionRoute
  ApiPiVerifyRoute: typeof ApiPiVerifyRoute
  ApiPiPaymentsApproveRoute: typeof ApiPiPaymentsApproveRoute
  ApiPiPaymentsCancelRoute: typeof ApiPiPaymentsCancelRoute
  ApiPiPaymentsCompleteRoute: typeof ApiPiPaymentsCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trust': {
      id: '/trust'
      path: '/trust'
      fullPath: '/trust'
      preLoaderRoute: typeof TrustRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/': {
      id: '/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof ContractsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/$id': {
      id: '/contracts/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof ContractsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts/new': {
      id: '/contracts/new'
      path: '/contracts/new'
      fullPath: '/contracts/new'
      preLoaderRoute: typeof ContractsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pi/session': {
      id: '/api/pi/session'
      path: '/api/pi/session'
      fullPath: '/api/pi/session'
      preLoaderRoute: typeof ApiPiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pi/verify': {
      id: '/api/pi/verify'
      path: '/api/pi/verify'
      fullPath: '/api/pi/verify'
      preLoaderRoute: typeof ApiPiVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pi/payments/approve': {
      id: '/api/pi/payments/approve'
      path: '/api/pi/payments/approve'
      fullPath: '/api/pi/payments/approve'
      preLoaderRoute: typeof ApiPiPaymentsApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pi/payments/cancel': {
      id: '/api/pi/payments/cancel'
      path: '/api/pi/payments/cancel'
      fullPath: '/api/pi/payments/cancel'
      preLoaderRoute: typeof ApiPiPaymentsCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pi/payments/complete': {
      id: '/api/pi/payments/complete'
      path: '/api/pi/payments/complete'
      fullPath: '/api/pi/payments/complete'
      preLoaderRoute: typeof ApiPiPaymentsCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  GuideRoute: GuideRoute,
  HowItWorksRoute: HowItWorksRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrustRoute: TrustRoute,
  WalletRoute: WalletRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  ContractsIdRoute: ContractsIdRoute,
  ContractsNewRoute: ContractsNewRoute,
  ContractsIndexRoute: ContractsIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPiSessionRoute: ApiPiSessionRoute,
  ApiPiVerifyRoute: ApiPiVerifyRoute,
  ApiPiPaymentsApproveRoute: ApiPiPaymentsApproveRoute,
  ApiPiPaymentsCancelRoute: ApiPiPaymentsCancelRoute,
  ApiPiPaymentsCompleteRoute: ApiPiPaymentsCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
